# Generated by Django 4.1.4 on 2023-01-06 07:10

from django.db import migrations
import os


def migrate_default_subjects(apps, schema_editor):
    Subject = apps.get_model("app","Subjects")
    Users = apps.get_model("auth","User")
    subject_list = ['Excel','Typing Test','Internet Search']
    user= Users.objects.create_user(username='admin', password= os.environ.get('ADMIN_PASSWORD'), is_superuser= True)

    for subj in subject_list:
        Subject.objects.create(
            subject = subj,
            created_by = user
        )

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_passageinstructioncontents_question_id_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_default_subjects, migrations.RunPython.noop)
    ]
