# Generated by Django 4.1.4 on 2023-01-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_title_passageinstructioncontents_question_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageinstructioncontents',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.allquestions'),
            preserve_default=False,
        ),
    ]
