# Generated by Django 4.1.4 on 2023-01-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_created_by_user_imagemultiplechoicequestions_created_by_and_more'),
        ('app', '0005_passageinstructioncontents_question_id'),
    ]

    operations = [
    ]
