# Generated by Django 4.1.4 on 2023-01-31 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20230130_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemultiplechoicequestions',
            old_name='created_by_user',
            new_name='created_by',
        ),
    ]
