# Generated by Django 4.1.4 on 2023-02-15 06:37

import app.utility.question_module_functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_candidateresultindividual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresultindividual',
            name='paper_set_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.papersetupdescription'),
        ),
        migrations.AlterField(
            model_name='candidateresultindividual',
            name='paper_subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.papersetupsubjectmap'),
        ),
        migrations.AlterField(
            model_name='candidateresultindividual',
            name='subject_question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subjectquestionmap'),
        ),
        migrations.AlterField(
            model_name='candidateresults',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.grades'),
        ),
        migrations.AlterField(
            model_name='excelquestions',
            name='question_title',
            field=models.CharField(max_length=200, unique=True, validators=[app.utility.question_module_functions.validate_check_null]),
        ),
        migrations.AlterField(
            model_name='papersetupdescription',
            name='paper_title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
