# Generated by Django 4.1.4 on 2023-02-07 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_rename_created_by_user_imagemultiplechoicequestions_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelquestions',
            name='screenshot',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='excelquestions',
            name='screenshot_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PaperHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('paper_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.papersetupdescription')),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paper_history',
            },
        ),
    ]
