# Generated by Django 4.1.4 on 2023-03-14 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_interviewparameter_personalinterview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInterviewMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidatedetails')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_interview_mapping',
            },
        ),
    ]
