# Generated by Django 4.1.4 on 2023-03-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_personalinterviewmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateeducationdetails',
            name='qualifications',
            field=models.CharField(choices=[('OTHER', 'other'), ('PG', 'Post Graduate'), ('UG', 'Under Graduate'), ('DIPLOMA', 'Diploma'), ('12', 'Higher Secondary'), ('10', 'Secondary')], max_length=24, null=True),
        ),
    ]
