# Generated by Django 4.1.4 on 2023-08-09 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_allquestions_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allquestions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='candidateeducationdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='candidatefamilydetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='candidateotherdetails',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='candidateresultindividual',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='candidateresults',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='candidatesourceofinformation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='candidateworkexperience',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='excelquestions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='grades',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='imagebasedsubjectivequestions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='imagemultiplechoicequestions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='interviewparameter',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='multipleimagechoicequestion',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paperhistory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='papersetupdescription',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='papersetuppassagemap',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='papersetupsubjectmap',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='passageinstructioncontents',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='personalinterview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='personalinterviewmap',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subjectivequestions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subjectquestionmap',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testlevels',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 6, 45, 0, 698134, tzinfo=datetime.timezone.utc)),
        ),
    ]
