MESSAGE = {
    "login": "Logged in successfully",
    "logout": "Logged out successfully",
    "invalid_credentials": "Invalid username or password",
    "no_data": "No data found",
    "invalid_page": "Page not found",
    "user_added": "User added successfully",
    "user_exist": "Username already taken",
    "user_update": "User updated successfully",
    "user_delete": "User deleted successfully",
    "user_not_found": "User not found",
    "subject_added": "Subject added successfully",
    "subject_update": "Subject updated successfully",
    "subject_exists": "Subject already exists",
    "subject_deleted": "Subject deleted successfully",
    "subject_not_found": "Subject does not exists",
    "content_added": "Content added successfully",
    "content_exist": "Content already exists",
    "content_updated": "Content updated successfully",
    "content_deleted": "Content deleted successfully",
    "content_not_found": "Content doesn't exists",
    "administrator_error": "Administrator cannot be deleted",
    "email_exist": "This email id already taken.",
    "question_deleted": "Question deleted successfully",
    "question_added": "Question added successfully",
    "question_not_found": "Question not found!",
    "question_update": "Question updated",
    "method_not_allowed": "Method not allowed",
    "question_updated": "Question updated successfully",
    "passage_not_found": "Passage does not exists",
    "wrong_method": "Method not exist",
    "null_id": "Invalid ID",
    "subject_link_error": "This question can not link with",
    "excel_without_title": "Can not create excel sheet without title",
    "error_occur": "Some error occur, Please try again !",
    "subjective_question_added": "Subjective question added successfully",
    "subjective_question_update": "Subjective question updated successfully",
    "subjective_question_deleted": "Subjective question deleted successfully",
    "subjective_question_exists": "Subjective question exists",
    "subjective_question_not_found": "Subjective question not found",
    "content_type_error": " is not a valid content type",
    "grade_add": "Grade added successfully",
    "grade_deleted": "Grade deleted successfully",
    "grade_exist": "Grade already exist in ",
    "grade_range": "Grade out of range.",
    "blank_field": "All fields required",
    "duplicate_options": "Option value should be unique.",
    "Select_subject": "Select atleast one subject",
    "paper_not_found": "Selected paper not found.",
    "paper_update": "Paper updated successfully,",
    "paper_deleted": "Paper deleted successfully",
    "task_completed": "Task completed, add questions now.",
    "questions_linked": "Questions linked successfully",
    "typing_test_type": "Passage type typing can only be linked with Typing test subject.",
    "paper_set": "Paper is set successfully.",
    "manual_marks": "Marks changed manually for a question",
    "invalid_candidate":"Invalid candidate id.",
    "not_appeared":"candidate didn't completed the paper",
    "not_authorized":"You are not authorized, contact HR",
    "export_success": "Exported successfully",
    "date_range_error":"From date is required",
    "no_data_for_search":"No data found for this search criteria",
}
